create table Category (id integer generated by default as identity (start with 1), name varchar(255), primary key (id));
create table Drink (id integer generated by default as identity (start with 1), cost varchar(255), name varchar(255), preparationTimeInMillis integer, category_id integer, primary key (id));
create table Order_ (id integer generated by default as identity (start with 1), customerName varchar(255), primary key (id));
create table order_drink (order_id integer not null, drink_id integer not null, unique (drink_id));
alter table Drink add constraint FK3F3A878E71E0A7 foreign key (category_id) references Category;
alter table order_drink add constraint FK74C95067C1A2FA2D foreign key (drink_id) references Drink;
alter table order_drink add constraint FK74C950672FE6F66D foreign key (order_id) references Order_;